# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Merde < Formula
  desc ""
  homepage ""
  version "0.0.4"

  depends_on "git" if OS.mac?
  depends_on "git" if OS.linux?

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/merde-bot/merde-cli/releases/download/v0.0.4/merde-cli_Darwin_x86_64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "f2cee04c18cbd3619e4bf28256719fe8e9eb30c4840cf6397daf1a59c3d4511c"

      def install
        bin.install "merde-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/merde-bot/merde-cli/releases/download/v0.0.4/merde-cli_Darwin_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "bef62d479a8843a86d4f2976640a9116cb78004d396f93f05d705d4ac9bfd8af"

      def install
        bin.install "merde-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/merde-bot/merde-cli/releases/download/v0.0.4/merde-cli_Linux_x86_64.tar.gz",
          headers: [
            "Accept: application/octet-stream",
            "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
          ]
        sha256 "af7ab6bd082192bdb6615e8910bc8fbdfec21405dcb352254dd8b8b3bed03426"

        def install
          bin.install "merde-cli"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/merde-bot/merde-cli/releases/download/v0.0.4/merde-cli_Linux_arm64.tar.gz",
          headers: [
            "Accept: application/octet-stream",
            "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
          ]
        sha256 "9f9a63431a1ff1103b98aeaea1f4edab09c752b3f72086fe0f1fd5793d18223b"

        def install
          bin.install "merde-cli"
        end
      end
    end
  end

  def caveats
    <<~EOS
      👋
    EOS
  end

  test do
    system "#{bin}/merde version"
  end
end
