# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Merde < Formula
  desc ""
  homepage ""
  version "0.0.5"

  depends_on "git" if OS.mac?
  depends_on "git" if OS.linux?

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/merde-bot/merde-cli/releases/download/v0.0.5/merde-cli_Darwin_x86_64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "e5eaf65de0cb075296fe82ad09244157255a18803c0ef06db99e27cd495fc7de"

      def install
        bin.install "merde-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/merde-bot/merde-cli/releases/download/v0.0.5/merde-cli_Darwin_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "5ffccf6e08fc71b0400c31a6bd517414c357a85d4b925b2c265d719906b9b5e0"

      def install
        bin.install "merde-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/merde-bot/merde-cli/releases/download/v0.0.5/merde-cli_Linux_x86_64.tar.gz",
          headers: [
            "Accept: application/octet-stream",
            "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
          ]
        sha256 "02c3cc3d0eb7ca50034adbc53d6f73a25ae4250cb81744c97a0b89d27b868347"

        def install
          bin.install "merde-cli"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/merde-bot/merde-cli/releases/download/v0.0.5/merde-cli_Linux_arm64.tar.gz",
          headers: [
            "Accept: application/octet-stream",
            "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
          ]
        sha256 "be5153633bb1cd0a30ccb63883f61d2dc1899d54bfa839bdc8091858b8be8e6a"

        def install
          bin.install "merde-cli"
        end
      end
    end
  end

  def caveats
    <<~EOS
      👋
    EOS
  end

  test do
    system "#{bin}/merde version"
  end
end
